# -*- coding: utf-8 -*-
"""1-arff2csv

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1r8oTVqbIjlOGJfxmcp-GoDHXOHDf52zf
"""

!pip install liac-arff # install arff but no use

import scipy.io.arff
import pandas as pd
import numpy as np
from sklearn.utils import resample # for Bootstrap sampling
import shutil
import os

# use to load ReLink original datasets, but dont need this
# import arff

# click load google drive
rootpath = "/content/drive/MyDrive/Colab Notebooks/1/"

datasets_original = "datasets-original/"
datasets_discretize = "datasets-discretize/"
datasets_log = "datasets-log/"
datasets_minmax = "datasets-min-max/"
datasets_standardize = "datasets-standardize/"

AEEEM = ["EQ", "JDT", "LC", "ML", "PDE"]
ReLink = ["Zxing", "Apache", "Safe"]
Columba = ["columba", "eclipse", "scarab"]
Promise = ["ant-1.3", "ant-1.4", "ant-1.5", "ant-1.6", "ant-1.7",
           "camel-1.0", "camel-1.2", "camel-1.4", "camel-1.6",
           "ivy-1.1", "ivy-1.4", "ivy-2.0",
           "jedit-3.2", "jedit-4.0", "jedit-4.1", "jedit-4.2", "jedit-4.3",
           "log4j-1.0", "log4j-1.1", "log4j-1.2",
           "lucene-2.0", "lucene-2.2", "lucene-2.4",
           "poi-1.5", "poi-2.0", "poi-2.5", "poi-3.0",
           "xalan-2.4", "xalan-2.5", "xalan-2.6", "xalan-2.7",
           "xerces-1.2", "xerces-1.3", "xerces-1.4"]

ARFF = "ARFF/"
CSV = "CSV/"

BOOTSTRAP = "BOOTSTRAP/"

def setDir(filepath):

    #if filepath not exist then create else delete all files then create ！

    if not os.path.exists(filepath):
        os.mkdir(filepath)
    else:
        pass

# change all the arff file to csv file

readfilepath = rootpath + datasets_original + ARFF

for i in range(len(AEEEM)):

  readfile = readfilepath + "AEEEM/" + AEEEM[i] + ".arff"
  data,meta = scipy.io.arff.loadarff(readfile) # NOTE: ReLink original has bug{Y,N}->error  correct is bug {Y,N}

  df = pd.DataFrame(data)

  # bug has a b'Y' and b'N'
  df["bug"] = (df["bug"]== b"Y").astype(int)  # then bug into N->0 Y->1 !!! all the bug label change to 1

  outfilepath = rootpath + datasets_original + CSV + "AEEEM/"
  setDir(outfilepath)

  df.to_csv(outfilepath+AEEEM[i]+".csv",index=False)
  print(AEEEM[i]+" end")

# change finished success



"""**下面是草稿**"""